<?php
declare(strict_types=1);
namespace App\Domain\Payments;
use App\Core\{Database,TenantContext};
use App\Domain\Authorization\PartyScopePredicate;
use App\Support\Money;

/** Sole invoice-outstanding authority: only active, non-reversed allocations reduce an invoice. */
final class OutstandingService {
 public function __construct(private Database $db,private PartyScopePredicate $scope){}
 public function rowsForContext(TenantContext $ctx,?string $partyRef=null):array{$p=[':f'=>$ctx->requireFranchise()];$w=["i.franchise_ref=:f","i.status='POSTED'",$this->scope->clause($ctx,'p',$p,'payments')];if($partyRef!==null&&$partyRef!==''){$w[]='i.party_ref=:party';$p[':party']=$partyRef;}return $this->age($this->rows(implode(' AND ',$w),$p));}
 /** Compatibility read for non-request internal callers. */
 public function invoiceRows(string $franchiseRef,?string $partyRef=null):array{$p=[':f'=>$franchiseRef];$w=["i.franchise_ref=:f","i.status='POSTED'"];if($partyRef){$w[]='i.party_ref=:party';$p[':party']=$partyRef;}return $this->rows(implode(' AND ',$w),$p);}
 public function withAgeing(string $franchiseRef,?string $partyRef=null):array{return $this->age($this->invoiceRows($franchiseRef,$partyRef));}
 public function pageForContext(TenantContext $ctx,array $filters):array{$rows=$this->rowsForContext($ctx,$filters['party_ref']??null);$from=$filters['from']??$filters['due_from']??null;$to=$filters['to']??$filters['due_to']??null;$bucket=$filters['bucket']??null;$rows=array_values(array_filter($rows,static function(array$row)use($from,$to,$bucket):bool{if($from!==null&&($row['dueDate']===null||$row['dueDate']<$from))return false;if($to!==null&&($row['dueDate']===null||$row['dueDate']>$to))return false;return $bucket===null||$bucket===''||$row['bucket']===$bucket;}));$sorts=['invoiceNumber'=>'invoiceNumber','partyName'=>'partyName','dueDate'=>'dueDate','balance'=>'balance','bucket'=>'bucket','daysOverdue'=>'daysOverdue','status'=>'status'];$sort=$sorts[(string)($filters['sort_by']??'')]??'dueDate';$dir=strtolower((string)($filters['sort_dir']??'asc'))==='desc'?-1:1;usort($rows,static function(array$a,array$b)use($sort,$dir):int{$av=$a[$sort]??null;$bv=$b[$sort]??null;if($av===$bv)return strcmp($a['invoiceRef'],$b['invoiceRef'])*$dir;if($av===null)return $dir;if($bv===null)return -$dir;if(in_array($sort,['balance','daysOverdue'],true))return ((float)$av<=>(float)$bv)*$dir;return strcmp((string)$av,(string)$bv)*$dir;});$page=max(1,(int)($filters['page']??1));$per=min(100,max(1,(int)($filters['per_page']??25)));$total=count($rows);return['rows'=>array_slice($rows,($page-1)*$per,$per),'meta'=>['page'=>$page,'per_page'=>$per,'total'=>$total,'total_pages'=>(int)ceil($total/$per)]];}
 public function dashboardForContext(TenantContext $ctx):array{$totals=['NOT_DUE'=>0,'0-30'=>0,'31-60'=>0,'61-90'=>0,'91-120'=>0,'120+'=>0,'UNCLASSIFIED'=>0];$total=0;foreach($this->rowsForContext($ctx)as$row){$amount=Money::fromDecimal($row['balance']);$total+=$amount;$totals[$row['bucket']??'UNCLASSIFIED']+=$amount;}$b=[];foreach($totals as$bucket=>$amount)$b[]=['bucket'=>$bucket,'total'=>(float)Money::toDecimal($amount)];return['available'=>true,'reason'=>null,'total'=>(float)Money::toDecimal($total),'buckets'=>$b];}
 private function rows(string $where,array $p):array{return $this->db->fetchAll("SELECT i.invoice_ref invoiceRef,i.invoice_no invoiceNumber,p.firm_name partyName,i.party_ref partyRef,i.due_date dueDate,i.grand_total invoiceAmount,COALESCE(SUM(CASE WHEN a.status='ACTIVE' AND pay.status NOT IN ('REVERSED','CANCELLED') THEN a.allocated_amount ELSE 0 END),0) allocatedAmount FROM invoices i JOIN parties p ON p.franchise_ref=i.franchise_ref AND p.party_ref=i.party_ref LEFT JOIN payment_allocations a ON a.franchise_ref=i.franchise_ref AND a.invoice_ref=i.invoice_ref LEFT JOIN payments pay ON pay.franchise_ref=a.franchise_ref AND pay.payment_ref=a.payment_ref WHERE $where GROUP BY i.invoice_ref,i.invoice_no,p.firm_name,i.party_ref,i.due_date,i.grand_total HAVING i.grand_total>COALESCE(SUM(CASE WHEN a.status='ACTIVE' AND pay.status NOT IN ('REVERSED','CANCELLED') THEN a.allocated_amount ELSE 0 END),0)",$p);}
 private function age(array $rows):array{$today=new \DateTimeImmutable('today');foreach($rows as&$row){$balance=Money::fromDecimal((string)$row['invoiceAmount'])-Money::fromDecimal((string)$row['allocatedAmount']);$row['invoiceAmount']=Money::toDecimal(Money::fromDecimal((string)$row['invoiceAmount']));$row['allocatedAmount']=Money::toDecimal(Money::fromDecimal((string)$row['allocatedAmount']));$row['balance']=Money::toDecimal($balance);$row['outstandingAmount']=$row['balance'];if(empty($row['dueDate'])){$row['daysOverdue']=null;$row['bucket']='UNCLASSIFIED';$row['status']=Money::fromDecimal($row['allocatedAmount'])>0?'Partial':'Unpaid';continue;}$days=(int)(new \DateTimeImmutable($row['dueDate']))->diff($today)->format('%r%a');$row['daysOverdue']=max(0,$days);$row['bucket']=$days<=0?'NOT_DUE':($days<=30?'0-30':($days<=60?'31-60':($days<=90?'61-90':($days<=120?'91-120':'120+'))));$row['status']=Money::fromDecimal($row['allocatedAmount'])>0?'Partial':'Unpaid';}unset($row);return $rows;}
}
