<?php
declare(strict_types=1);
namespace App\Domain\Payments;
use App\Core\{Database,RefGenerator,SequenceService};use App\Core\Exceptions\{ConflictException,ValidationException};use App\Support\Money;
use App\Core\TenantContext;use App\Domain\Authorization\PartyScopePredicate;

/** Authoritative PDC lifecycle; PENDING instruments have no financial effect. */
final class PdcService {
 public function __construct(private Database$db,private SequenceService$sequences,private PartyScopePredicate$scope){}
 public function listScoped(TenantContext$c,int$page,int$per,?string$party=null):array{$p=[':f'=>$c->requireFranchise()];$w=['d.franchise_ref=:f',$this->scope->clause($c,'p',$p)];if($party){$w[]='d.party_ref=:party';$p[':party']=$party;}$where=implode(' AND ',$w);$total=(int)$this->db->fetchColumn("SELECT COUNT(*) FROM pdcs d JOIN parties p ON p.franchise_ref=d.franchise_ref AND p.party_ref=d.party_ref WHERE $where",$p);$off=($page-1)*$per;$rows=$this->db->fetchAll("SELECT d.pdc_ref,d.party_ref,p.firm_name party_name,d.amount,d.cheque_number,d.bank_name,d.due_date,d.status,d.payment_ref,d.created_at,d.realized_at,d.bounced_at,d.cancelled_at FROM pdcs d JOIN parties p ON p.franchise_ref=d.franchise_ref AND p.party_ref=d.party_ref WHERE $where ORDER BY d.id DESC LIMIT $per OFFSET $off",$p);return['rows'=>$rows,'meta'=>['page'=>$page,'per_page'=>$per,'total'=>$total,'total_pages'=>(int)ceil($total/$per)]];}
 public function findScoped(TenantContext$c,string$ref):?array{$p=[':f'=>$c->requireFranchise(),':r'=>$ref];$s=$this->scope->clause($c,'p',$p);return $this->db->fetchOne("SELECT d.* FROM pdcs d JOIN parties p ON p.franchise_ref=d.franchise_ref AND p.party_ref=d.party_ref WHERE d.franchise_ref=:f AND d.pdc_ref=:r AND $s",$p);}
 /** Registration locks the scoped party, rather than trusting a party_ref supplied by the client. */
 public function register(TenantContext$c,string$party,string$amount,?string$cheque,?string$bank,?string$due,string$actor):array{$paise=Money::fromDecimal($amount);if($paise<=0||!$cheque)throw new ValidationException('INVALID_PDC','Amount and instrument reference are required.');$f=$c->requireFranchise();return $this->db->transaction(function()use($c,$f,$party,$paise,$cheque,$bank,$due,$actor){$p=[':f'=>$f,':party'=>$party];$s=$this->scope->clause($c,'p',$p);$active=$this->db->fetchOne("SELECT p.party_ref FROM parties p WHERE p.franchise_ref=:f AND p.party_ref=:party AND p.status='ACTIVE' AND $s FOR UPDATE",$p);if(!$active)throw new ValidationException('PARTY_NOT_FOUND','Active party was not found.');$ref=RefGenerator::generate('pdc');$this->db->insert('pdcs',['pdc_ref'=>$ref,'org_ref'=>$c->orgRef,'franchise_ref'=>$f,'party_ref'=>$party,'amount'=>Money::toDecimal($paise),'cheque_number'=>$cheque,'bank_name'=>$bank,'due_date'=>$due,'status'=>'PENDING','created_by_ref'=>$actor]);return['pdc_ref'=>$ref,'party_ref'=>$party,'status'=>'PENDING'];});}
 public function realize(TenantContext$c,string$ref,string$actor):array{return $this->db->transaction(function()use($c,$ref,$actor){$f=$c->requireFranchise();$p=$this->scopedForUpdate($c,$ref);$this->pending($p);if($p['payment_ref'])throw new ConflictException('PDC_ALREADY_REALIZED','PDC already has a linked payment.');$no=$this->sequences->next($f,'PAYMENT',date('Y-m-d'));$pay=RefGenerator::generate('pay');$this->db->insert('payments',['payment_ref'=>$pay,'payment_no'=>$no,'org_ref'=>$p['org_ref'],'franchise_ref'=>$f,'party_ref'=>$p['party_ref'],'payment_date'=>date('Y-m-d'),'amount'=>$p['amount'],'allocated_amount'=>'0.00','mode'=>'PDC','reference_no'=>$p['cheque_number'],'remarks'=>'PDC '.$p['pdc_ref'],'status'=>'RECORDED','created_by_ref'=>$actor]);$this->db->prepare("UPDATE pdcs SET status='REALIZED',payment_ref=?,realized_by_ref=?,realized_at=NOW() WHERE franchise_ref=? AND pdc_ref=? AND status='PENDING' AND payment_ref IS NULL")->execute([$pay,$actor,$f,$ref]);return['pdc_ref'=>$ref,'payment_ref'=>$pay,'status'=>'REALIZED'];});}
 public function bounce(TenantContext$c,string$ref,string$actor,string$reason):array{return $this->db->transaction(function()use($c,$ref,$actor,$reason){$f=$c->requireFranchise();$p=$this->scopedForUpdate($c,$ref);$this->pending($p);if(trim($reason)==='')throw new ValidationException('PDC_BOUNCE_REASON_REQUIRED','Bounce reason is required.');$this->db->prepare("UPDATE pdcs SET status='BOUNCED',bounce_reason=?,bounced_by_ref=?,bounced_at=NOW() WHERE franchise_ref=? AND pdc_ref=? AND status='PENDING'")->execute([$reason,$actor,$f,$ref]);return['pdc_ref'=>$ref,'status'=>'BOUNCED'];});}
 public function cancel(TenantContext$c,string$ref,string$actor,string$reason):array{return $this->db->transaction(function()use($c,$ref,$actor,$reason){$f=$c->requireFranchise();$p=$this->scopedForUpdate($c,$ref);$this->pending($p);$this->db->prepare("UPDATE pdcs SET status='CANCELLED',cancel_reason=?,cancelled_by_ref=?,cancelled_at=NOW() WHERE franchise_ref=? AND pdc_ref=? AND status='PENDING'")->execute([$reason,$actor,$f,$ref]);return['pdc_ref'=>$ref,'status'=>'CANCELLED'];});}
 private function scopedForUpdate(TenantContext$c,string$ref):?array{$p=[':f'=>$c->requireFranchise(),':r'=>$ref];$s=$this->scope->clause($c,'party',$p);return $this->db->fetchOne("SELECT d.* FROM pdcs d JOIN parties party ON party.franchise_ref=d.franchise_ref AND party.party_ref=d.party_ref WHERE d.franchise_ref=:f AND d.pdc_ref=:r AND $s FOR UPDATE",$p);}
 private function pending(?array$p):void{if(!$p)throw new ValidationException('PDC_NOT_FOUND','PDC was not found.');if($p['status']!=='PENDING')throw new ValidationException('INVALID_PDC_TRANSITION','PDC is not pending.');}
}
