<?php
declare(strict_types=1);
namespace App\Domain\Reports;
use App\Core\{Database,TenantContext};use App\Core\Exceptions\ValidationException;

/** Read-only tenant/scope query layer shared by Dashboard and report adapters. */
final class ScopedAnalyticsService {
 public function __construct(private Database $db){}
 public function dashboard(TenantContext$c):array{$team=[];if($c->scopeFor('internalUsers')==='ALL')$team=$this->db->fetchAll("SELECT user_ref userRef,full_name name FROM users WHERE franchise_ref=? AND status='ACTIVE' ORDER BY full_name",[$c->requireFranchise()]);return ['leads'=>$this->leadSummary($c),'follow_ups'=>$this->count($c,'followUps','follow_ups','assigned_user_ref',null,"status='PENDING' AND next_follow_up_at < CURDATE()+INTERVAL 1 DAY"),'orders'=>$this->orderSummary($c),'outstanding'=>['available'=>false,'reason'=>'AGEING_POLICY_PENDING','total'=>null,'buckets'=>[]],'near_expiry'=>$this->nearExpiry($c),'sales_team'=>['available'=>$c->scopeFor('internalUsers')==='ALL','rows'=>$team]];}
 public function report(TenantContext$c,string$key,array$f):array{$map=[
 'lead-source'=>['leads','leads l','l.assigned_user_ref',null,"l.lead_source source,COUNT(*) totalLeads,SUM(l.status='CONVERTED') converted",'l.lead_source'],
 'response-time'=>['leads','leads l','l.assigned_user_ref',null,"l.lead_ref leadRef,l.firm_name leadName,l.lead_source source,l.created_at createdDate,l.first_response_at respondedAt",'l.created_at'],
 'conversion'=>['leads','leads l','l.assigned_user_ref',null,"l.status stage,COUNT(*) count",'l.status'],
 'sales-team-productivity'=>['internalUsers','users u','u.user_ref',null,"u.user_ref userRef,u.full_name name",'u.user_ref'],
 'territory-sales'=>['orders','orders o','o.sales_user_ref','o.party_ref',"COALESCE(d.district_name,'Unassigned') district,COUNT(*) orders,SUM(o.grand_total) totalSales",'d.district_name'],
 'party-sales'=>['orders','orders o','o.sales_user_ref','o.party_ref',"p.firm_name partyName,COUNT(*) orders,SUM(o.grand_total) totalSales",'p.firm_name'],
 'product-sales'=>['orders','orders o','o.sales_user_ref','o.party_ref',"pr.product_name productName,SUM(oi.paid_qty) qtySold,SUM(oi.free_qty) freeQty,SUM(oi.line_total) netSales",'pr.product_name'],
 'scheme-utilization'=>['schemes','orders o','o.sales_user_ref','o.party_ref',"s.scheme_name schemeName,COUNT(*) timesApplied,SUM(oi.free_qty) freeQtyGiven,SUM(oi.line_total) netSales",'s.scheme_name'],
 'order-status'=>['orders','orders o','o.sales_user_ref','o.party_ref',"o.status status,COUNT(*) count,SUM(o.grand_total) totalValue",'o.status'],
 'dispatch-pending'=>['dispatch','orders o','o.sales_user_ref','o.party_ref',"o.order_ref invoiceNo,p.firm_name partyName,o.status,o.order_date orderDate,o.grand_total total",'o.order_date'],
 'batch-inventory'=>['inventory','inventory_batches b',null,null,"pr.product_name productName,b.batch_no batchNo,b.expiry_date expiryDate,(b.on_hand_qty-b.reserved_qty) availableQty,b.status",'b.expiry_date'],
 'near-expiry'=>['nearExpiry','inventory_batches b',null,null,"pr.product_name productName,b.batch_no batchNo,b.expiry_date expiryDate,DATEDIFF(b.expiry_date,CURDATE()) daysLeft,(b.on_hand_qty-b.reserved_qty) availableQty",'b.expiry_date'],
 'territory-violations'=>['territory','orders o','o.sales_user_ref','o.party_ref',"o.order_ref invoiceNo,p.firm_name partyName,o.remarks reason,o.order_date orderDate",'o.order_date'],
 'webhook-failures'=>['webhooks','webhook_events w',null,null,"w.source_ref source,w.event_ref eventType,w.received_at receivedAt,w.status,w.error_message errorMessage",'w.received_at'],
 'whatsapp-delivery'=>['notifications','notifications n',null,'n.party_ref',"n.party_ref recipientName,n.event_type templateName,n.status,n.created_at sentAt",'n.created_at']];
 if($key==='payment-outstanding')throw new ValidationException('REPORT_BLOCKED_BY_DECISION','payment-outstanding requires approved ageing authority.');if(!isset($map[$key]))throw new ValidationException('INVALID_REPORT_TYPE','Unknown report.');[$module,$from,$owner,$party,$select,$group]=$map[$key];$p=[':f'=>$c->requireFranchise()];$where=[''.$this->alias($from).'.franchise_ref=:f',$this->scope($c,$module,$owner,$party,$p)];$joins=$this->joins($key);if(!empty($f['from'])){$where[]=$this->dateCol($key).'>=:from';$p[':from']=$f['from'];}if(!empty($f['to'])){$where[]=$this->dateCol($key).'<=:to';$p[':to']=$f['to'];}$clause=implode(' AND ',$where);$allowed=['source'=>'source','stage'=>'stage','name'=>'name','district'=>'district','partyName'=>'partyName','productName'=>'productName','schemeName'=>'schemeName','status'=>'status','orderDate'=>'orderDate','expiryDate'=>'expiryDate','receivedAt'=>'receivedAt','sentAt'=>'sentAt'];$sort=$allowed[$f['sort_by']??'']??$group;$dir=strtolower((string)($f['sort_dir']??'asc'))==='desc'?'DESC':'ASC';$page=max(1,(int)($f['page']??1));$per=min(100,max(1,(int)($f['per_page']??25)));$offset=($page-1)*$per;$total=(int)$this->db->fetchColumn("SELECT COUNT(*) FROM (SELECT 1 FROM $from $joins WHERE $clause GROUP BY $group) scoped",$p);$sql="SELECT $select FROM $from $joins WHERE $clause GROUP BY $group ORDER BY $sort $dir LIMIT $per OFFSET $offset";return ['rows'=>$this->db->fetchAll($sql,$p),'meta'=>['report_key'=>$key,'page'=>$page,'per_page'=>$per,'total'=>$total,'total_pages'=>(int)ceil($total/$per)]];}
 private function scope(TenantContext$c,string$m,?string$o,?string$party,array&$p):string{$s=$c->scopeFor($m);if($c->isSuper()||$s==='ALL')return'1=1';if($s==='NONE')return'1=0';if($s==='OWN'){$p[':u']=$c->userRef;return$o?"$o=:u":'1=0';}if($s==='TEAM'){$users=array_values(array_unique(array_merge([$c->userRef],$c->teamUserRefs)));if(!$o||!$users)return'1=0';$x=[];foreach($users as$i=>$u){$k=':u'.$i;$p[$k]=$u;$x[]=$k;}return"$o IN (".implode(',',$x).')';}if($s==='TERRITORY'&&$party&&$c->territoryRefs){$x=[];foreach($c->territoryRefs as$i=>$t){$k=':t'.$i;$p[$k]=$t;$x[]=$k;}return "EXISTS(SELECT 1 FROM party_territories pt WHERE pt.franchise_ref=:f AND pt.party_ref=$party AND pt.status='ACTIVE' AND pt.territory_ref IN(".implode(',',$x).'))";}return'1=0';}
 private function count(TenantContext$c,string$m,string$table,string$owner,?string$party,string$extra):array{$p=[':f'=>$c->requireFranchise()];return ['count'=>(int)$this->db->fetchColumn("SELECT COUNT(*) FROM $table x WHERE x.franchise_ref=:f AND ".$this->scope($c,$m,"x.$owner",$party,$p)." AND $extra",$p)];}
 private function leadSummary(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'leads','l.assigned_user_ref',null,$p);return $this->db->fetchOne("SELECT SUM(DATE(l.created_at)=CURDATE()) new_today,SUM(l.first_response_at IS NULL) first_response_pending FROM leads l WHERE l.franchise_ref=:f AND $s",$p)??[];}
 private function orderSummary(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'orders','o.sales_user_ref','o.party_ref',$p);return $this->db->fetchOne("SELECT SUM(o.status NOT IN ('DRAFT','CANCELLED')) active,SUM(o.status='CANCELLED') cancelled,SUM(o.territory_status='OVERRIDDEN') territory_overrides FROM orders o WHERE o.franchise_ref=:f AND $s",$p)??[];}
 private function nearExpiry(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'nearExpiry',null,null,$p);return $this->db->fetchOne("SELECT COUNT(*) batch_count FROM inventory_batches b WHERE b.franchise_ref=:f AND $s AND b.status='SALEABLE' AND b.expiry_date<=DATE_ADD(CURDATE(),INTERVAL 180 DAY)",$p)??[];}
 private function alias(string$f):string{return trim(explode(' ',$f)[1]??$f);}private function joins(string$k):string{return match($k){'territory-sales'=>" JOIN parties p ON p.franchise_ref=o.franchise_ref AND p.party_ref=o.party_ref LEFT JOIN districts d ON d.district_ref=p.district_ref",'party-sales','dispatch-pending','territory-violations'=>" JOIN parties p ON p.franchise_ref=o.franchise_ref AND p.party_ref=o.party_ref",'product-sales','scheme-utilization'=>" JOIN order_items oi ON oi.franchise_ref=o.franchise_ref AND oi.order_ref=o.order_ref JOIN products pr ON pr.franchise_ref=oi.franchise_ref AND pr.product_ref=oi.product_ref ".($k==='scheme-utilization'?"LEFT JOIN schemes s ON s.franchise_ref=oi.franchise_ref AND s.scheme_ref=oi.scheme_ref":''),'batch-inventory','near-expiry'=>" JOIN products pr ON pr.franchise_ref=b.franchise_ref AND pr.product_ref=b.product_ref",default=>''};}private function dateCol(string$k):string{return match($k){'lead-source','response-time','conversion'=>'l.created_at','webhook-failures'=>'w.received_at','whatsapp-delivery'=>'n.created_at','batch-inventory','near-expiry'=>'b.expiry_date',default=>'o.order_date'};}
}
