<?php
declare(strict_types=1);
namespace App\Domain\Reports;
use App\Core\{Database,TenantContext};use App\Core\Exceptions\ValidationException;use App\Domain\Payments\OutstandingService;

/** Tenant/scope-safe, report-specific dashboard DTOs. Monetary expressions remain DECIMAL in SQL. */
final class ScopedAnalyticsService {
 private const SLA_HOURS=4,NEAR_EXPIRY_DAYS=180;
 public function __construct(private Database $db,private OutstandingService $outstanding){}
 public function dashboard(TenantContext$c):array{return ['leads'=>$this->leads($c),'follow_ups'=>$this->followUps($c),'orders'=>$this->orders($c),'outstanding'=>$this->dashboardOutstanding($c),'near_expiry'=>$this->nearExpiry($c),'sales_team'=>$this->team($c)];}
 private function dashboardOutstanding(TenantContext$c):array{return $c->can('payments','view')?$this->outstanding->dashboardForContext($c):['available'=>false,'reason'=>'PAYMENTS_VIEW_FORBIDDEN','total'=>null,'buckets'=>[]];}
 public function report(TenantContext$c,string$key,array$f):array{if($key==='payment-outstanding')return $this->paymentOutstanding($c,$f);$d=$this->definition($key);if(!$d)throw new ValidationException('INVALID_REPORT_TYPE','Unknown report.');[$m,$from,$owner,$party,$select,$group,$joins,$date,$sorts,$extra]=$d;$p=[':f'=>$c->requireFranchise()];$w=[$this->alias($from).'.franchise_ref=:f',$this->scope($c,$m,$owner,$party,$p)];if(!empty($f['from'])){$w[]="$date>=:from";$p[':from']=$f['from'];}if(!empty($f['to'])){$w[]="$date<=:to";$p[':to']=$f['to'];}if(!empty($f['status'])){$w[]=$this->alias($from).'.status=:status';$p[':status']=strtoupper((string)$f['status']);}if($extra)$w[]=$extra;$where=implode(' AND ',$w);$sort=$sorts[$f['sort_by']??'']??$group;$dir=strtolower((string)($f['sort_dir']??'asc'))==='desc'?'DESC':'ASC';$page=max(1,(int)($f['page']??1));$per=min(100,max(1,(int)($f['per_page']??25)));$off=($page-1)*$per;$total=(int)$this->db->fetchColumn("SELECT COUNT(*) FROM (SELECT 1 FROM $from $joins WHERE $where GROUP BY $group) scoped",$p);$rows=$this->db->fetchAll("SELECT $select FROM $from $joins WHERE $where GROUP BY $group ORDER BY $sort $dir LIMIT $per OFFSET $off",$p);return ['rows'=>$rows,'meta'=>['report_key'=>$key,'page'=>$page,'per_page'=>$per,'total'=>$total,'total_pages'=>(int)ceil($total/$per)]];}
 private function paymentOutstanding(TenantContext$c,array$f):array{$result=$this->outstanding->pageForContext($c,$f);$rows=[];foreach($result['rows']as$row)$rows[]=['invoiceNumber'=>$row['invoiceNumber'],'partyName'=>$row['partyName'],'dueDate'=>$row['dueDate'],'balance'=>(float)$row['balance'],'bucket'=>$row['bucket'],'status'=>$row['status']];$result['rows']=$rows;$result['meta']['report_key']='payment-outstanding';return $result;}
 /** Each select list is the public DTO contract, not a generic persistence row. */
 private function definition(string$k):?array{return [
 'lead-source'=>['leads','leads l','l.assigned_user_ref',null,"COALESCE(l.lead_source,'Unknown') source,COUNT(*) totalLeads,SUM(l.status='CONVERTED') converted,ROUND(100*SUM(l.status='CONVERTED')/NULLIF(COUNT(*),0),2) conversionPct","COALESCE(l.lead_source,'Unknown')",'','l.created_at',['source'=>'source','totalLeads'=>'totalLeads','converted'=>'converted','conversionPct'=>'conversionPct'],''],
 'response-time'=>['leads','leads l','l.assigned_user_ref',null,"l.lead_ref leadRef,COALESCE(l.firm_name,l.contact_name) leadName,COALESCE(l.lead_source,'Unknown') source,l.created_at createdDate,l.first_response_at respondedAt,ROUND(TIMESTAMPDIFF(MINUTE,l.created_at,COALESCE(l.first_response_at,NOW()))/60,1) durationHours,CASE WHEN TIMESTAMPDIFF(MINUTE,l.created_at,COALESCE(l.first_response_at,NOW()))>".(self::SLA_HOURS*60)." THEN 'Yes' ELSE 'No' END breached",'l.lead_ref','', 'l.created_at',['leadRef'=>'leadRef','leadName'=>'leadName','source'=>'source','createdDate'=>'createdDate','respondedAt'=>'respondedAt','durationHours'=>'durationHours','breached'=>'breached'],''],
 'conversion'=>['leads','leads l','l.assigned_user_ref',null,'l.status stage,COUNT(*) count','l.status','', 'l.created_at',['stage'=>'stage','count'=>'count'],''],
 'sales-team-productivity'=>['internalUsers','users u','u.user_ref',null,"u.user_ref userId,u.full_name name,(SELECT COUNT(*) FROM leads l WHERE l.franchise_ref=u.franchise_ref AND l.assigned_user_ref=u.user_ref) leadsCount,(SELECT COUNT(*) FROM leads l WHERE l.franchise_ref=u.franchise_ref AND l.assigned_user_ref=u.user_ref AND l.status='CONVERTED') convertedCount,(SELECT COUNT(*) FROM orders o WHERE o.franchise_ref=u.franchise_ref AND o.sales_user_ref=u.user_ref AND o.status NOT IN ('DRAFT','CANCELLED')) ordersCount,COALESCE((SELECT SUM(o.grand_total) FROM orders o WHERE o.franchise_ref=u.franchise_ref AND o.sales_user_ref=u.user_ref AND o.status NOT IN ('DRAFT','CANCELLED')),0) ordersValue",'u.user_ref,u.full_name','', 'u.created_at',['userId'=>'userId','name'=>'name','leadsCount'=>'leadsCount','convertedCount'=>'convertedCount','ordersCount'=>'ordersCount','ordersValue'=>'ordersValue'],"u.status='ACTIVE'"],
 'territory-sales'=>['orders','orders o','o.sales_user_ref','o.party_ref',"COALESCE(st.state_name,'Unknown') state,COALESCE(d.district_name,'Unknown') district,COUNT(*) orders,COALESCE(SUM(o.grand_total),0) totalSales",'st.state_name,d.district_name',"JOIN parties p ON p.franchise_ref=o.franchise_ref AND p.party_ref=o.party_ref LEFT JOIN states st ON st.state_ref=p.state_ref LEFT JOIN districts d ON d.district_ref=p.district_ref",'o.order_date',['state'=>'state','district'=>'district','orders'=>'orders','totalSales'=>'totalSales'],"o.status NOT IN ('DRAFT','CANCELLED')"],
 'party-sales'=>['orders','orders o','o.sales_user_ref','o.party_ref','p.party_ref partyId,p.firm_name partyName,COUNT(*) orders,COALESCE(SUM(o.grand_total),0) totalSales','p.party_ref,p.firm_name','JOIN parties p ON p.franchise_ref=o.franchise_ref AND p.party_ref=o.party_ref','o.order_date',['partyId'=>'partyId','partyName'=>'partyName','orders'=>'orders','totalSales'=>'totalSales'],"o.status NOT IN ('DRAFT','CANCELLED')"],
 'product-sales'=>['orders','orders o','o.sales_user_ref','o.party_ref','pr.product_ref productId,pr.product_name productName,COALESCE(SUM(oi.paid_qty),0) qtySold,COALESCE(SUM(oi.free_qty),0) freeQty,COALESCE(SUM(oi.line_total),0) netSales','pr.product_ref,pr.product_name','JOIN order_items oi ON oi.franchise_ref=o.franchise_ref AND oi.order_ref=o.order_ref JOIN products pr ON pr.franchise_ref=oi.franchise_ref AND pr.product_ref=oi.product_ref','o.order_date',['productId'=>'productId','productName'=>'productName','qtySold'=>'qtySold','freeQty'=>'freeQty','netSales'=>'netSales'],"o.status NOT IN ('DRAFT','CANCELLED')"],
 'scheme-utilization'=>['schemes','orders o','o.sales_user_ref','o.party_ref','s.scheme_ref schemeId,s.scheme_name schemeName,COUNT(*) timesApplied,COALESCE(SUM(oi.free_qty),0) freeQtyGiven,COALESCE(SUM(oi.line_total),0) netSales','s.scheme_ref,s.scheme_name','JOIN order_items oi ON oi.franchise_ref=o.franchise_ref AND oi.order_ref=o.order_ref JOIN schemes s ON s.franchise_ref=oi.franchise_ref AND s.scheme_ref=oi.scheme_ref','o.order_date',['schemeId'=>'schemeId','schemeName'=>'schemeName','timesApplied'=>'timesApplied','freeQtyGiven'=>'freeQtyGiven','netSales'=>'netSales'],"o.status NOT IN ('DRAFT','CANCELLED')"],
 'order-status'=>['orders','orders o','o.sales_user_ref','o.party_ref','o.status status,COUNT(*) count,COALESCE(SUM(o.grand_total),0) totalValue','o.status','', 'o.order_date',['status'=>'status','count'=>'count','totalValue'=>'totalValue'],''],
 'dispatch-pending'=>['dispatch','orders o','o.sales_user_ref','o.party_ref','o.order_no invoiceNo,p.firm_name partyName,o.status status,o.order_date orderDate,o.grand_total total','o.order_ref,o.order_no,p.firm_name,o.status,o.order_date,o.grand_total','JOIN parties p ON p.franchise_ref=o.franchise_ref AND p.party_ref=o.party_ref','o.order_date',['invoiceNo'=>'invoiceNo','partyName'=>'partyName','status'=>'status','orderDate'=>'orderDate','total'=>'total'],"o.status IN ('CONFIRMED','PROCESSING')"],
 'batch-inventory'=>['inventory','inventory_batches b',null,null,'pr.product_name productName,b.batch_no batchNo,b.expiry_date expiryDate,(b.on_hand_qty-b.reserved_qty) availableQty,b.status status,((b.on_hand_qty-b.reserved_qty)*pr.mrp) stockValue','b.batch_ref,pr.product_name,b.batch_no,b.expiry_date,b.on_hand_qty,b.reserved_qty,b.status,pr.mrp','JOIN products pr ON pr.franchise_ref=b.franchise_ref AND pr.product_ref=b.product_ref','b.expiry_date',['productName'=>'productName','batchNo'=>'batchNo','expiryDate'=>'expiryDate','availableQty'=>'availableQty','status'=>'status','stockValue'=>'stockValue'],''],
 'near-expiry'=>['nearExpiry','inventory_batches b',null,null,'pr.product_name productName,b.batch_no batchNo,b.expiry_date expiryDate,DATEDIFF(b.expiry_date,CURDATE()) daysLeft,(b.on_hand_qty-b.reserved_qty) availableQty,((b.on_hand_qty-b.reserved_qty)*pr.mrp) stockValue','b.batch_ref,pr.product_name,b.batch_no,b.expiry_date,b.on_hand_qty,b.reserved_qty,pr.mrp','JOIN products pr ON pr.franchise_ref=b.franchise_ref AND pr.product_ref=b.product_ref','b.expiry_date',['productName'=>'productName','batchNo'=>'batchNo','expiryDate'=>'expiryDate','daysLeft'=>'daysLeft','availableQty'=>'availableQty','stockValue'=>'stockValue'],"b.status='SALEABLE' AND b.on_hand_qty>b.reserved_qty AND b.expiry_date>CURDATE() AND b.expiry_date<=DATE_ADD(CURDATE(),INTERVAL ".self::NEAR_EXPIRY_DAYS." DAY)"],
 'territory-violations'=>['territory','orders o','o.sales_user_ref','o.party_ref','o.order_no invoiceNo,p.firm_name partyName,t.reason reason,o.order_date orderDate','o.order_ref,o.order_no,p.firm_name,t.reason,o.order_date','JOIN territory_overrides t ON t.franchise_ref=o.franchise_ref AND t.order_ref=o.order_ref JOIN parties p ON p.franchise_ref=o.franchise_ref AND p.party_ref=o.party_ref','o.order_date',['invoiceNo'=>'invoiceNo','partyName'=>'partyName','reason'=>'reason','orderDate'=>'orderDate'],''],
 'webhook-failures'=>['webhooks','webhook_events w',null,null,'w.source_ref source,w.event_ref eventType,w.received_at receivedAt,w.status status,w.error_message errorMessage','w.event_ref','', 'w.received_at',['source'=>'source','eventType'=>'eventType','receivedAt'=>'receivedAt','status'=>'status','errorMessage'=>'errorMessage'],"w.status='FAILED'"],
 'whatsapp-delivery'=>['notifications','notifications n',null,'n.party_ref',"COALESCE(p.firm_name,n.party_ref,'') recipientName,n.event_type templateName,n.status status,n.created_at sentAt",'n.notification_ref,n.party_ref,p.firm_name,n.event_type,n.status,n.created_at','LEFT JOIN parties p ON p.franchise_ref=n.franchise_ref AND p.party_ref=n.party_ref','n.created_at',['recipientName'=>'recipientName','templateName'=>'templateName','status'=>'status','sentAt'=>'sentAt'],"n.channel='WHATSAPP'"]][$k]??null;}
 private function leads(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'leads','l.assigned_user_ref',null,$p);$m=$this->db->fetchOne("SELECT SUM(DATE(l.created_at)=CURDATE()) newToday,SUM(l.assigned_user_ref IS NULL) unassignedCount,SUM(CASE WHEN l.first_response_at IS NULL THEN TIMESTAMPDIFF(MINUTE,l.created_at,NOW())>".(self::SLA_HOURS*60)." ELSE TIMESTAMPDIFF(MINUTE,l.created_at,l.first_response_at)>".(self::SLA_HOURS*60)." END) slaBreachedCount FROM leads l WHERE l.franchise_ref=:f AND $s",$p)??[];$raw=$this->db->fetchAll("SELECT DATE_FORMAT(l.created_at,'%d %b') date,COUNT(*) totalCount,SUM(CASE WHEN l.first_response_at IS NULL THEN TIMESTAMPDIFF(MINUTE,l.created_at,NOW())>".(self::SLA_HOURS*60)." ELSE TIMESTAMPDIFF(MINUTE,l.created_at,l.first_response_at)>".(self::SLA_HOURS*60)." END) breachedCount FROM leads l WHERE l.franchise_ref=:f AND $s AND l.created_at>=CURDATE()-INTERVAL 6 DAY GROUP BY DATE(l.created_at)",$p);$by=[];foreach($raw as$r)$by[$r['date']]=$r;$trend=[];for($i=6;$i>=0;$i--){$d=(new \DateTimeImmutable("-$i days"))->format('d M');$trend[]=$by[$d]??['date'=>$d,'totalCount'=>0,'breachedCount'=>0];}$counts=[];foreach($this->db->fetchAll("SELECT l.status status,COUNT(*) count FROM leads l WHERE l.franchise_ref=:f AND $s GROUP BY l.status",$p)as$r)$counts[$r['status']]=(int)$r['count'];$series=[];foreach(['NEW','ASSIGNED','CONTACTED','INTERESTED','FOLLOW_UP','DOCUMENTS_PENDING','QUALIFIED','CONVERTED','LOST','REJECTED','ARCHIVED']as$status)$series[]=['status'=>$status,'count'=>$counts[$status]??0];return $m+['slaThresholdHours'=>self::SLA_HOURS,'slaTrend'=>$trend,'conversionSeries'=>$series];}
 private function followUps(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'followUps','x.assigned_user_ref',null,$p);return $this->db->fetchOne("SELECT SUM(x.status='PENDING' AND DATE(x.next_follow_up_at)=CURDATE()) dueTodayCount,SUM(x.status='PENDING' AND x.next_follow_up_at<CURDATE()) overdueCount FROM follow_ups x WHERE x.franchise_ref=:f AND $s",$p)??[];}
 private function orders(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'orders','o.sales_user_ref','o.party_ref',$p);$m=$this->db->fetchOne("SELECT SUM(o.status NOT IN ('DRAFT','CANCELLED')) activeCount,SUM(o.territory_status='OVERRIDDEN') territoryViolationCount,SUM(o.status='CANCELLED') cancelledCount,SUM(o.status IN ('CONFIRMED','PROCESSING')) dispatchPendingCount FROM orders o WHERE o.franchise_ref=:f AND $s",$p)??[];$raw=$this->db->fetchAll("SELECT DATE_FORMAT(o.order_date,'%b %y') month,COALESCE(SUM(o.grand_total),0) total,COUNT(*) orderCount FROM orders o WHERE o.franchise_ref=:f AND $s AND o.status NOT IN ('DRAFT','CANCELLED') AND o.order_date>=DATE_SUB(CURDATE(),INTERVAL 5 MONTH) GROUP BY YEAR(o.order_date),MONTH(o.order_date)",$p);$by=[];foreach($raw as$r)$by[$r['month']]=$r;$trend=[];for($i=5;$i>=0;$i--){$month=(new \DateTimeImmutable("first day of -$i month"))->format('M y');$trend[]=$by[$month]??['month'=>$month,'total'=>0,'orderCount'=>0];}return $m+['salesTrend'=>$trend];}
 private function nearExpiry(TenantContext$c):array{$p=[':f'=>$c->requireFranchise()];$s=$this->scope($c,'nearExpiry',null,null,$p);return $this->db->fetchOne("SELECT COUNT(*) count,COALESCE(SUM((b.on_hand_qty-b.reserved_qty)*pr.mrp),0) stockValue FROM inventory_batches b JOIN products pr ON pr.franchise_ref=b.franchise_ref AND pr.product_ref=b.product_ref WHERE b.franchise_ref=:f AND $s AND b.status='SALEABLE' AND b.on_hand_qty>b.reserved_qty AND b.expiry_date>CURDATE() AND b.expiry_date<=DATE_ADD(CURDATE(),INTERVAL ".self::NEAR_EXPIRY_DAYS." DAY)",$p)??[];}
 private function team(TenantContext$c):array{if($c->scopeFor('internalUsers')!=='ALL')return['available'=>false,'rows'=>[]];$p=[':f'=>$c->requireFranchise()];$r=$this->db->fetchAll("SELECT u.user_ref userId,u.full_name name,(SELECT COUNT(*) FROM leads l WHERE l.franchise_ref=u.franchise_ref AND l.assigned_user_ref=u.user_ref) leadsCount,(SELECT COUNT(*) FROM leads l WHERE l.franchise_ref=u.franchise_ref AND l.assigned_user_ref=u.user_ref AND l.status='CONVERTED') convertedCount,(SELECT COUNT(*) FROM orders o WHERE o.franchise_ref=u.franchise_ref AND o.sales_user_ref=u.user_ref AND o.status NOT IN ('DRAFT','CANCELLED')) ordersCount,COALESCE((SELECT SUM(o.grand_total) FROM orders o WHERE o.franchise_ref=u.franchise_ref AND o.sales_user_ref=u.user_ref AND o.status NOT IN ('DRAFT','CANCELLED')),0) ordersValue FROM users u WHERE u.franchise_ref=:f AND u.status='ACTIVE' HAVING leadsCount>0 OR ordersCount>0 ORDER BY ordersValue DESC",$p);return['available'=>true,'rows'=>$r];}
 private function scope(TenantContext$c,string$m,?string$o,?string$party,array&$p):string{$s=$c->scopeFor($m);if($c->isSuper()||$s==='ALL')return'1=1';if($s==='NONE')return'1=0';if($s==='OWN'){$p[':u']=$c->userRef;return$o?"$o=:u":'1=0';}if($s==='TEAM'){$u=array_values(array_unique(array_merge([$c->userRef],$c->teamUserRefs)));if(!$o||!$u)return'1=0';$q=[];foreach($u as$i=>$v){$n=":u$i";$p[$n]=$v;$q[]=$n;}return "$o IN (".implode(',',$q).')';}if($s==='TERRITORY'&&$party&&$c->territoryRefs){$q=[];foreach($c->territoryRefs as$i=>$v){$n=":t$i";$p[$n]=$v;$q[]=$n;}return "EXISTS(SELECT 1 FROM party_territories pt WHERE pt.franchise_ref=:f AND pt.party_ref=$party AND pt.status='ACTIVE' AND pt.territory_ref IN(".implode(',',$q).'))';}return'1=0';}
 private function alias(string$f):string{return trim(explode(' ',$f)[1]??$f);}
}
