<?php
declare(strict_types=1);
namespace App\Http\Controllers\Api\V1\Admin;
use App\Core\{Request,Response,TenantContext,Validation};use App\Core\Exceptions\NotFoundException;use App\Domain\Authorization\AuthorizationService;use App\Domain\Audit\AuditService;use App\Domain\Payments\PdcService;
final class PdcsController {public function __construct(private PdcService$pdcs,private AuthorizationService$auth,private AuditService$audit){}
 public function index(Request$r):Response{$c=TenantContext::get();$this->auth->requirePermission($c,'payments','view');$page=max(1,(int)$r->query('page',1));$per=min(100,max(1,(int)$r->query('per_page',25)));$party=$c->isDistributor()?$c->partyRef:$r->query('party_ref');$x=$this->pdcs->listScoped($c,$page,$per,$party);return Response::json(200,$x['rows'],$x['meta']);}
 public function show(Request$r):Response{$c=TenantContext::get();$this->auth->requirePermission($c,'payments','view');$x=$this->pdcs->findScoped($c,(string)$r->param('ref'));if(!$x||($c->isDistributor()&&$x['party_ref']!==$c->partyRef))throw new NotFoundException('PDC_NOT_FOUND','PDC not found.');return Response::json(200,$x);}
 public function store(Request$r):Response{$c=TenantContext::get();$this->auth->requirePermission($c,'payments','pdc');$d=Validation::validate($r->all(),['party_ref'=>'required|string','amount'=>'required|numeric','cheque_number'=>'required|string']);$x=$this->pdcs->register($c,$d['party_ref'],(string)$d['amount'],$d['cheque_number'],$r->input('bank_name'),$r->input('due_date'),$c->userRef);$this->audit->log(ctx:$c,category:'BUSINESS',action:'pdc.registered',entityType:'pdc',entityRef:$x['pdc_ref'],after:$x);return Response::json(201,$x);}
 public function realize(Request$r):Response{return $this->mutate($r,'pdc.realized',fn($c,$ref)=>$this->pdcs->realize($c,$ref,$c->userRef));}
 public function bounce(Request$r):Response{$d=Validation::validate($r->all(),['reason'=>'required|string|min:2']);return $this->mutate($r,'pdc.bounced',fn($c,$ref)=>$this->pdcs->bounce($c,$ref,$c->userRef,$d['reason']));}
 public function cancel(Request$r):Response{$d=Validation::validate($r->all(),['reason'=>'required|string|min:2']);return $this->mutate($r,'pdc.cancelled',fn($c,$ref)=>$this->pdcs->cancel($c,$ref,$c->userRef,$d['reason']));}
 private function mutate(Request$r,string$action,callable$fn):Response{$c=TenantContext::get();$this->auth->requirePermission($c,'payments','pdc');$ref=(string)$r->param('ref');$x=$fn($c,$ref);$this->audit->log(ctx:$c,category:'BUSINESS',action:$action,entityType:'pdc',entityRef:$ref,after:$x);return Response::json(200,$x);}}
